<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE codelean [
<!ELEMENT codelean(to, from, subject, message)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT message (#PCDATA)>
]>
<codelean>
  <to>My Readers</to>
  <from>ThiDK</from>
  <subject>A Message to my readers</subject>
  <message>Welcome to codelean.vn</massage>
</codelean>
